apiVersion: v1
kind: Template
labels:
  template: Guacamole
metadata:
  annotations:
    description: Guacamole XRDP and VNC over HTML5
    iconClass: icon-tomcat
    tags: guacamole
  creationTimestamp: null
  name: guacamole
objects:
- apiVersion: "v1"
  kind: "ImageStream"
  metadata:
    name: "guacd"
  spec:
    dockerImageRepository: ${GUACD_IMAGE_NAME}

- apiVersion: "v1"
  kind: "ImageStream"
  metadata:
    name: "guacamole"
  spec:
    dockerImageRepository: ${GUACAMOLE_IMAGE_NAME}

- apiVersion: v1
  kind: Service
  metadata:
    name: guacd
  spec:
    ports:
    - port: 4822
      protocol: TCP
      targetPort: 4822
    selector:
      name: guacd

- apiVersion: v1
  kind: Service
  metadata:
    name: guacamole
  spec:
    ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      name: guacamole

- apiVersion: v1
  kind: Service
  metadata:
    name: guacamole-db
  spec:
    ports:
    - port: 3306
      protocol: TCP
      targetPort: 3306
    selector:
      name: guacamole-db

- apiVersion: v1
  kind: Route
  metadata:
    name: guacamole
  spec:
    to:
      kind: Service
      name: guacamole

- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      description: Defines how to deploy the application server
    name: guacd
  spec:
    replicas: 1
    selector:
      name: guacd
    strategy:
      type: Rolling
    template:
      metadata:
        labels:
          name: guacd
        name: guacd
      spec:
        containers:
        - name: guacd
          image: guacd:latest
          ports:
          - containerPort: 4822
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - guacd
        from:
          kind: ImageStreamTag
          name: guacd:latest
      type: ImageChange

- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      description: Defines how to deploy the application server
    name: guacamole
  spec:
    replicas: 1
    selector:
      name: guacamole
    strategy:
      type: Rolling
    template:
      metadata:
        labels:
          name: guacamole
        name: guacamole
      spec:
        containers:
        - image: guacamole:latest
          name: guacamole
          ports:
          - containerPort: 8080
          env:
          - name: MYSQL_USER
            value: ${MYSQL_USER}
          - name: MYSQL_PASSWORD
            value: ${MYSQL_PASSWORD}
          - name: MYSQL_DATABASE
            value: ${MYSQL_DATABASE}
          - name: MYSQL_HOSTNAME
            value: ${MYSQL_DATABASE}
          - name: MYSQL_PORT
            value: 3306
          - name: GUACD_HOSTNAME
            value: guacd
          - name: GUACD_PORT
            value: 4822

          - name: MYSQL_NAME
            value: mysqlhasafirstnameitsoscar
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - guacamole
        from:
          kind: ImageStreamTag
          name: guacamole:latest
      type: ImageChange

- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: "guacamole-db"
    labels:
      app: guacamole-db
  spec:
    replicas: 1
    selector:
      name: guacamole-db
    strategy:
      resources: {}
      recreateParams:
        timeoutSeconds: 600
      type: Recreate
    template:
      metadata:
        creationTimestamp: null
        labels:
          name: guacamole-db
      spec:
        volumes:
          - name: container-scripts
            persistentVolumeClaim:
              claimName: container-scripts
          - emptyDir: {}
            name: guacamole-db-data
        containers:
        - env:
          - name: STARTUP_SQL
            value: 001-create-schema.sql 002-create-admin-user.sql
          - name: MYSQL_USER
            value: ${MYSQL_USER}
          - name: MYSQL_PASSWORD
            value: ${MYSQL_PASSWORD}
          - name: ${MYSQL_DATABASE}
            value: ${MYSQL_DATABASE}
          - name: MYSQL_ROOT_PASSWORD
            value: ${MYSQL_PASSWORD}
          image: registry.access.redhat.com/rhscl/mariadb-101-rhel7@sha256:86ee10d39753b2d54503b6570a4511fbe5581b87be7db77b8f9517abbab355fb
          imagePullPolicy: IfNotPresent
          name: mariadb-101-rhel7
          ports:
          - containerPort: 3306
            protocol: TCP
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 3306
            timeoutSeconds: 1
          readinessProbe:
            exec:
              command:
              - /bin/sh
              - -i
              - -c
              - MYSQL_PWD="$MYSQL_PASSWORD" mysql -h 127.0.0.1 -u $MYSQL_USER -D $MYSQL_DATABASE
                -e 'SELECT 1'
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources: {}
          volumeMounts:
          - name: container-scripts
            mountPath: /usr/share/container-scripts/mysql/
          - name: guacamole-db-data
            mountPath: /var/lib/mysql/data
          terminationMessagePath: /dev/termination-log
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - guacamole-db
        from:
          kind: ImageStreamTag
          namespace: openshift
          name: mariadb:10.1
      type: ImageChange


parameters:
- description: Guacd Image
  name: GUACD_IMAGE_NAME
  value: docker.io/glyptodon/guacd
  required: true
- description: Guacamole Image
  name: GUACAMOLE_IMAGE_NAME
  value: docker.io/glyptodon/guacamole
  required: true
- description: A secret string used to configure the GitHub webhook.
  displayName: GitHub Webhook Secret
  from: '[a-zA-Z0-9]{40}'
  generate: expression
  name: GITHUB_WEBHOOK_SECRET

- description: The username for the MySQL user
  name: MYSQL_USER
  value: guacamole_user
  required: true
- description: The password for the MySQL password
  name: MYSQL_PASSWORD
  value: guacamole_pass
  required: true
- description: The name of the MySQL database
  name: MYSQL_DATABASE
  value: guacamole_db
required: true
