apiVersion: "v1"
kind: "DeploymentConfig"
metadata:
  name: "guacamole-db"
  labels:
    app: guacamole-db
spec:
  replicas: 1
  selector:
    name: guacamole-db
  strategy:
    resources: {}
    recreateParams:
      timeoutSeconds: 600
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: guacamole-db
    spec:
      volumes:
        - name: container-scripts
          persistentVolumeClaim:
            claimName: container-scripts
        - emptyDir: {}
          name: guacamole-db-data
      containers:
      - env:
        - name: STARTUP_SQL
          value: 001-create-schema.sql 002-create-admin-user.sql
        - name: MYSQL_USER
          value: guacamole_user
        - name: MYSQL_PASSWORD
          value: some_password
        - name: MYSQL_DATABASE
          value: guacamole_db
        - name: MYSQL_ROOT_PASSWORD
          value: some_password
        image: registry.access.redhat.com/rhscl/mariadb-101-rhel7@sha256:86ee10d39753b2d54503b6570a4511fbe5581b87be7db77b8f9517abbab355fb
        imagePullPolicy: IfNotPresent
        name: mariadb-101-rhel7
        ports:
        - containerPort: 3306
          protocol: TCP
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 3306
          timeoutSeconds: 1
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -i
            - -c
            - MYSQL_PWD="$MYSQL_PASSWORD" mysql -h 127.0.0.1 -u $MYSQL_USER -D $MYSQL_DATABASE
              -e 'SELECT 1'
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        volumeMounts:
        - name: container-scripts
          mountPath: /usr/share/container-scripts/mysql/
        - name: guacamole-db-data
          mountPath: /var/lib/mysql/data
        terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - guacamole-db
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: mariadb:10.1
    type: ImageChange
